nome = str(input('Digite seu nome completo: ')).strip()
print('Nome com letras maiúsculas', nome.upper())
print('Nome com letras minúsculas', nome.lower())
print('Total de letras sem espaço', len(nome) - nome.count(' '))
dividido = nome.split()
print('Qtd de letras do primeiro nome', len(dividido[0]))
